<div data-role="header" data-position="fixed" data-fullscreen="true" data-theme="a">
	<h1>Smart Bicycle</h1>  		           	
    <a href="info.html" data-icon="info" data-iconpos="notext"></a>
    <a data-rel="back" data-icon="back" data-iconpos="notext"></a>
    
    <div data-role="navbar" data-iconpos="top" id="headerMenu">
        <ul>
            <li><a href="javascript:btnDate();">Date</a></li>
            <li><a href="graph.jsp">Graph</a></li>
            <li><a href="track.jsp">Track</a></li>
            <li><a href="gallery.jsp">Gallery</a></li>
            <li><a href="trace.jsp">Alert</a></li>
        </ul>
    </div>   
</div>